### ISSUE TITLE
Update dwsutil for missing crds rsyncnodedatamovements & rsynctemplates

### ISSUE THREAD

**Issue by billhpe** [NearNodeFlash/dwsutil#12]

**Comment by NateThornton** [comment]
Both CRDs are obsolete

**Comment by billhpe** [comment]
Okay, that's good to know, I can close this issue then.  A new install using nnf-deploy installed these CRDs in the system and dwsutil reported them as unrecognized, so I wrote this ticket..  We should create a new ticket to remove the CRD cruft  from getting installed.
