### ISSUE TITLE
Add Storages object dump to system investigate

### ISSUE THREAD

**Issue by billhpe** [NearNodeFlash/dwsutil#13]

**Comment by NateThornton** [comment]
Manually adding objects to investigate seems unsustainable over the long term (although perhaps we've reached the end of the line for NNF?). Do you think instead we could just query the CRDs and investigate any `*.hpe.com$` resource?

**Comment by billhpe** [comment]
The intention of system investigate is to facilitate the investigation of issues with the setup of a given environment.  dwsutil does actually do a wildcard search of cray CRDs, and reports those that it does not recognize as well as those that it would expect to find.  I think that there is value in this effort as this can be used in a customer environment rather than asking our customer to issue a bunch of kubectl commands and then analyzing the output.

**Comment by NateThornton** [comment]
So this is a validation that a particular CRD is present?

**Comment by billhpe** [comment]
This particular issue has to do with Storages, there is a different issue that addresses CRDs.  The answer to your question is yes, dwsutil offers a diagnostic mode that will let you know if any expected CRDs are missing.  It doesn't attempt to confirm their structure or validity, just their presence in the system.

**Comment by billhpe** [comment]
oops...closed the wrong issue.
